## tinted-jjui (https://github.com/vic/tinted-jjui)
# Scheme name: Da One Gray
# Scheme author: NNB (https://github.com/NNBnh)
# Template author: Victor Borja <vborja@apache.org> (https://github.com/vic)

"text"      = { fg = "#ffffff" }
"dimmed"    = { fg = "#888888" }
"title"     = { fg = "#6bb8ff", bold = true }
"shortcut"  = { fg = "#e799ff" }
"matched"   = { fg = "#ff9470" }
"border"    = { fg = "#888888" }
":selected"  = { bg = "#282828", fg = "#ffffff", bold = true }

"source_marker" = { bg = "#8af5ff", fg = "#181818", bold = true }
"target_marker" = { bg = "#98c379", fg = "#181818", bold = true }
