[ui]

[preview]
position = "bottom"
show_at_start = true
width_percentage = 50

[[bindings]]
key = "enter"
action = "revisions.open_details"
scope = "revisions"
desc = "details"

[[bindings]]
key = "d"
action = "revisions.open_inline_describe"
scope = "revisions"
desc = "inline describe"
