#! /bin/sh

sxhkd &

bspc monitor -d 1 2 3 4 5 6 7 8 9 10

bspc config border_width         5
bspc config window_gap          20
bspc config top_padding 		31

bspc config normal_border_color "#1b1d21"
bspc config focused_border_color "#45484f"
bspc config presel_feedback_color "#747c84"

bspc config split_ratio         0.5
bspc config borderless_monocle  true
bspc config gapless_monocle     true
bspc config click_to_focus		true
bspc config single_monocle 		true

bspc rule -a firefox desktop='^1'
bspc rule -a qutebrowser desktop='^1'
bspc rule -a emacs desktop='^3' state=tiled
bspc rule -a Emacs desktop='^3' state=tiled
bspc rule -a Steam desktop='^4' state=tiled
bspc rule -a Steam.exe desktop='^4' state=tiled
bspc rule -a telegram-desktop desktop='^5'
bspc rule -a TelegramDesktop desktop='^5'
bspc rule -a whatsie desktop='^5'
bspc rule -a Whatsie desktop='^5'
bspc rule -a discord desktop='^6'
bspc rule -a csgo_linux64 desktop='^10'
bspc rule -a love state=floating

~/.scripts/detect_csgo.sh &
feh --bg-scale ~/Pictures/wallpaper2.jpg
compton -b
dunst &
mpd
polybar top &
# qutebrowser --backend=webengine &
firefox &
whatsie &
telegram-desktop &
steam-native &
