#! /bin/sh

[[ -f ~/.Xresources ]] && xrdb -merge -I$HOME ~/.Xresources

sxhkd &

bspc monitor -d 1 2 3 4 5 6 7 8 9 10

bspc config border_width				4
bspc config window_gap					0
bspc config split_ratio					0.5
bspc config borderless_monocle			true
bspc config gapless_monocle				true
bspc config click_to_focus				true
bspc config single_monocle				true
bspc config focus_follows_pointer 		false
bspc config normal_border_color 		"#444444"
bspc config focused_border_color 		"#aaaaaa"
bspc config presel_feedback_color		"#222222"
bspc config initial_polarity second_child

bspc rule -a Firefox desktop='^1'
bspc rule -a Emacs state='tiled'
bspc rule -a emacs state='tiled'
bspc rule -a Steam desktop='^4' split_dir='east' state='tiled'
bspc rule -a corebird desktop='^5'
bspc rule -a Corebird desktop='^5'
bspc rule -a discord desktop='^6'
bspc rule -a csgo_linux64 desktop='^10'

bspc rule -a albert border=off focus=on

xsetroot -cursor_name left_ptr
xset r rate 250 40

urxvtd &

# scratchpad
# bspc rule -a scratchpad|URxvt sticky=on state=floating locked=on &
# urxvtc -name scratchpad -e ~/bin/scratch &

# feh --bg-scale ~/images/Mascaloona\ -\ Dakshin\ \(21-9\)\ \(2560\ x\ 1080\).jpg &
feh --bg-tile ~/images/wallpaper_grid.png &
compton -b
albert &
dunst &
polybar bottom &
mpd &
nextcloud &
firefox &
