#! /bin/sh

sxhkd &

bspc monitor HDMI-0 -d 1 2 3 4 5 6 7 8 9 10
# bspc monitor DVI-D-0 -d 9 10

bspc config border_width         		3
bspc config window_gap           		32
bspc config -m HDMI-0 top_padding 		36

bspc config normal_border_color 		"#14161a"
bspc config focused_border_color 		"#45aeb6"
bspc config presel_feedback_color 		"#282828"

bspc config split_ratio         		0.5
bspc config borderless_monocle  		true
bspc config gapless_monocle     		true
bspc config click_to_focus				true
bspc config single_monocle 				true

bspc rule -a Firefox desktop='^1'
bspc rule -a qutebrowser desktop='^1'
bspc rule -a emacs desktop='^3' state=tiled
bspc rule -a Emacs desktop='^3' state=tiled
bspc rule -a Steam desktop='^4' state=tiled
bspc rule -a Steam.exe desktop='^4' state=tiled
bspc rule -a corebird desktop='^5'
bspc rule -a Corebird desktop='^5'
bspc rule -a discord desktop='^6'
bspc rule -a csgo_linux64 desktop='^10'
bspc rule -a love state=floating

bspc rule -a scratchpad sticky=on state=floating hidden=on locked=on
termite --class scratchpad -e ~/.scripts/scratchpad_terminal.sh &

~/.scripts/detect_csgo.sh &
feh --bg-tile ~/images/black_linen_v2.png
~/.scripts/polybar_wrapper.sh &
compton -b
firefox &
corebird &
steam-native &
emacs &
mpd &
/usr/lib/gnome-settings-daemon/gsd-xsettings &
/usr/lib/mate-polkit/polkit-mate-authentication-agent-1 &

