%hidden thm_fg="#d9dee3"
%hidden thm_dim="#4d4d4d"
%hidden thm_tab_bg="#202020"
%hidden thm_active="#f7c843"
%hidden thm_inactive="#56d4dd"
%hidden thm_border="#4d4d4d"
%hidden thm_border_active="#56d4dd"
%hidden thm_badge_fg="#1e2030"
%hidden thm_msg_fg="#8bd5ca"
%hidden thm_msg_bg="#363a4f"
source-file ~/.config/tmux/theme.conf
