%hidden thm_fg="#24292f"
%hidden thm_dim="#8c959f"
%hidden thm_tab_bg="#e6e7ec"
%hidden thm_active="#a04908"
%hidden thm_inactive="#0033b3"
%hidden thm_border="#e6e7ec"
%hidden thm_border_active="#0033b3"
%hidden thm_badge_fg="#ffffff"
%hidden thm_msg_fg="#0f5d68"
%hidden thm_msg_bg="#dbeef0"
source-file ~/.config/tmux/theme.conf
