set -g status on
set -g status-position bottom
set -g status-style "bg=default,fg=$thm_fg"
set -g status-justify left
set -g status-left ""
set -g status-right "#[bg=default,fg=$thm_dim] #S "
set -g status-right-length 50

setw -g window-status-format "#[bg=default,fg=$thm_inactive]#[bg=$thm_inactive,fg=$thm_tab_bg,bold]#I #[bg=$thm_tab_bg,fg=$thm_inactive,bold] #W #[bg=default,fg=$thm_tab_bg]"
setw -g window-status-current-format "#[bg=default,fg=$thm_active]#[bg=$thm_active,fg=$thm_tab_bg,bold]#I #[bg=$thm_tab_bg,fg=$thm_active,bold] #W #[bg=default,fg=$thm_tab_bg]"
setw -g window-status-separator " "

set -g pane-border-style "fg=$thm_border"
set -g pane-active-border-style "fg=$thm_border_active"
set -g pane-border-status top
set -g pane-border-format "#{?window_zoomed_flag,#[fg=$thm_border_active]#[bg=$thm_border_active]#[fg=$thm_badge_fg]#[bold] FULLSCREEN #[fg=$thm_border_active]#[bg=default],} [#P/#{window_panes}] #T "
set -g pane-border-indicators both
set -g pane-border-lines single

set -g message-style "fg=$thm_msg_fg,bg=$thm_msg_bg"
set -g message-command-style "fg=$thm_msg_fg,bg=$thm_msg_bg"
setw -g clock-mode-colour "$thm_msg_fg"
